
<!-- <div class="form" style="border:1px solid black; width:30vw; padding: 15px"> -->
    <h2>Bmi Calaculator</h2>
    <form method="POST" action="<?php echo $this->getUrl('bmicalculator/user/form'); ?>">
        <div>
        <div>
            <label for="user_name">User Name : </label>
            <input type="text" name="ccc_bmi_calculator[user_name]" id="user_name" >
        </div>
        <div >
            <label for="weight">Weight : </label>
            <input type="number" name="ccc_bmi_calculator[weight]" id="weight">
            <select id="dropdown">
                <option value="option1">>Kilogram </option>
                <option value="option2">>Weight </option></select>
        </div>

        <div>
        <label for="height">:Height </label>
            <input type="number" name="ccc_bmi_calculator[height]" id="height">
            <select id="dropdown">
                <option value="option1">>Meter</option>
                <option value="option2">>Feet</option></select>
        </div>
        
      <div>
          <input type="submit" value="Submit">
        </div>  
